# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{faster_rubygems}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2009-10-29}
  s.extra_rdoc_files = [
    "README"
  ]


  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "examples/require_fast_start.rb",
     "examples/require_rubygems_normal.rb",
     "ext/mkrf_conf.rb",
     "install.rb",
     "lib/frubygems.rb",
     "lib/rubygems_fast.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{faster gem loading}
  s.test_files = [
    "examples/require_fast_start.rb",
     "examples/require_rubygems_normal.rb"
  ]
  s.extensions = ["ext/mkrf_conf.rb"]

  s.post_install_message = "

installed! require 'frubygems' now

"

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
